### PR TITLE
[WIP] Edits to visualisation tutorial

### PR DESCRIPTION
**Pull request by KirstieJane**
- [x] I'm ready to merge

* **What's the context for this pull request?** 

- [ ] **rename small coeffcient to small world coefficient**
  I don't think it is clear what "small coefficient" is. I think it needs to be adjusted to "small world coefficient".
- [ ]  **rename "real" network to "original" network**
  Based on a comment from @islast in https://github.com/WhitakerLab/scona/pull/121/. This is changed in quite a few places
- [ ] **adjust legends**
  They now refer to the "Observed network" rather than "Real network". 
- [ ] **rename `create_df_sns_barplot`**
  I assume that anything that starts with `df` is a dataframe, so I changed the name of this function.
- [ ] **flip order of rich club legend**
  Put the observed (real, original) network on top in the legend.

I've also pulled a few changes from master. They should disappear from the PR once you've updated your fork ✨ 

* **What's new?**
The only major changes _should_ just be in the tutorial...

The rest are all (hopefully) quite small opinion changes.

* **What should a reviewer feedback on?**
Please check that I haven't missed anything!

* **Does anything need to be updated after merge?** 
_(e.g the wiki or the WhitakerLab website)_

### CODE REVIEW

**Comment by wingedRuslan** [comment]
@KirstieJane, thanks for the changes!
- Rename `small_coefficient` - I also was a little confused, so really good to have it renamed 
- Change real network to original network; 
I've addressed this point in [PR#121](https://github.com/WhitakerLab/scona/pull/121) and committed my changes (3 last commits), so I will have to resolve merge conflicts. It will not be a problem though, cause changes are pretty much the same :)

**Comment by KirstieJane** [comment]
Gotcha @wingedRuslan! Thank you - I'll fix the merge conflicts, don't worry.

Just going through the tutorial now - hoping to be able to approve soon ✨

**Comment by wingedRuslan** [comment]
@KirstieJane Thanks for your improvements to the tutorial! Looks awesome! :sparkles: 
Are you ready to merge? :smiley:

**Comment by KirstieJane** [comment]
Go for it!

**Pull request merged**
