### PR TITLE
Updates to interactive plotting tutorial

### PR DESCRIPTION
**Pull request by KirstieJane**
- [x] I'm ready to merge

* **What's the context for this pull request?** 
_(this is a good place to reference any issues that this PR addresses)_

I've gone through the tutorial and I really love it. Well done!

There's an outstanding issue for you to address, but this PR can be merged to your branch and we can work from https://github.com/WhitakerLab/scona/pull/145

* **What's new?**

Here's a list of some of my changes:

- [x] A few linting changes
- [x] Added `vmin` and `vmax` to a function
- [x] Restructure and text added to 3D tutorial, renamed
- [x] Renamed global viz tutorial (visualisations didn't make sense as a name now there are multiple ones!)
- [x] Adjusted default of `view_connectome_3d` to show top 2% of edges rather than all (which is basically never going to be used).
- [x] **removed non-interactive examples**
  Don't worry! I haven't deleted it permanently. I just think this notebook is so large that we're better of keeping it focused _just_ on the interactive plots and putting `plot_connectome` in a different notebook.

* **What should a reviewer feedback on?**

Check I haven't messed anything up!

* **Does anything need to be updated after merge?** 
_(e.g the wiki or the WhitakerLab website)_

### CODE REVIEW

**Comment by wingedRuslan** [comment]
@KirstieJane, that's totally fine! You are making a great tutorial and made some good changes to code. 


A few things I would like you to consider:

1) Interactive visualization tutorial is already of size 40+ MB. 

2) I've noticed that you are using
```
ConnectomeView = view_nodes_3d(G10)
ConnectomeView
```

I guess you can add more info about `ConnectomeView`: [Nilearn doc](https://nilearn.github.io/modules/generated/nilearn.plotting.view_markers.html)
> ConnectomeView : plot of the markers.
It can be saved as an html page or rendered (transparently) by the Jupyter notebook. Useful methods are :
‘resize’ to resize the plot displayed in a Jupyter notebook
‘save_as_html’ to save the plot to a file
‘open_in_browser’ to save the plot and open it in a web browser.

Links to source code, cause the nilearn doc on the website does not fully cover these aspects:
[open-in-browser](https://github.com/nilearn/nilearn/blob/43b9990bc7ce063fd5ddd4d73583969c8121ca20/nilearn/plotting/js_plotting_utils.py#L169)
[resize](https://github.com/nilearn/nilearn/blob/43b9990bc7ce063fd5ddd4d73583969c8121ca20/nilearn/plotting/js_plotting_utils.py#L125)
[save-as-html](https://github.com/nilearn/nilearn/blob/43b9990bc7ce063fd5ddd4d73583969c8121ca20/nilearn/plotting/js_plotting_utils.py#L162)

Once Isla told me that some scientists perform brain analysis on a cluster, so they have a command-line interface. So, in this case, they *still* can have these interactive visualisations, for instance,
```
# save viz to as ConnectomeView
ConnectomeView = view_nodes_3d(G10)

# save as html file
ConnectomeView.save_as_html(file_name="my-lovely-viz.html")

# viz will be saved in the current directory
# move this file from cluster to your machine
```

You can try it yourself and see that the figure in the html file is the same as in the jupyter notebook. One can interactively view and save as a png.

**Comment by KirstieJane** [comment]
That sounds great @wingedRuslan! I'll add a note about saving as html.

I don't know what to do about the tutorial being so large though! Any ideas??

**Comment by wingedRuslan** [comment]
@KirstieJane, I was also thinking about reducing the size of the tutorial when I was writing it. 

The reason for the large size is because interactive visualizations are "heavy" to be saved as an output of running `viz_function` in jupyter notebook (and also in terms of RAM memory). So my best idea is to limit the number of outputs by maybe commenting on the function-call or/and viewing the results. I understand that it is not a good solution though.
```
# do not make the output
# ConnectomeView = view_nodes_3d(G10)

# do not view the output
# ConnectomeView
```

Another idea is to have 2 versions of this tutorial, e.g. **interactive_viz_extended_tutorial.ipynb** and **interactive_viz_basic_tutorial.ipynb**. Make them identical but include more examples to the extended tutorial.

**Comment by KirstieJane** [comment]
I think we can probably upload the tutorial with no outputs - that would make the file much smaller in the repo? And then when we merge in the PR we can do a squash merge so that the interim files we've saved along the way don't appear in the main repo - what do you think?

**Comment by KirstieJane** [comment]
Heya! I didn't manage to get the update on how to save the file into the tutorial - would you mind having a bash at adding that please?

Thanks @wingedRuslan - this can be merged!

**Comment by wingedRuslan** [comment]
@KirstieJane, sure, I will include info on how to save a ConnectomeView as an html file!

**Pull request merged**
